arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  max_recurs: 2
  max_brdf_rays: 200
  max_recur_rays: 3
  infinity_border: False
  appdim_noise_std: 0.5
  # world_bounces: 40000
  # world_bounces: 2048000
  detach_inter: False
  world_bounces: 0
  # world_bounces: 10000
  # world_bounces: 204800
  max_normal_similarity: 0.87
  use_diffuse: True
  max_floater_loss: 1
  cold_start_bg_iters: 0
  detach_world_normal: 1000
  selector:
    _target_: modules.pt_selectors.TopNWeight
    max_selected: 2500000
    bounces_per_ray: 1000
    weight_thres: 1e-4

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 2
    shrink_freq: 0
    dynamic_batchsize: False
    sample_mode: multi_jitter
    # test_sample_mode: single_jitter
    # test_sample_mode: midpoint
    threshold: 1e-3
    grid_size: 128
    bound: 1.5

    # _target_: samplers.alphagrid.AlphaGridSampler
    # _partial_: True
    # enable_alpha_mask: False
    # nEnvSamples: 0
    # update_list: [4000, 8000]
    # multiplier: 1
    # threshold: 0.0001

    # _target_: samplers.raymarch.Raymarcher
    # _partial_: True
    # max_samples: 100000
    # grid_size: 256
    # max_steps: 1024

  rf: 'placeholder'

  brdf_sampler:
    _target_: models.brdf.GGXSampler
    _partial_: True

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  brdf:
    _target_: models.brdf.MLPBRDF
    _partial_: True
    # pbr: True

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # num_layers: 4
    # feape: 0
    # featureC: 128
    num_layers: 4
    feape: 0
    dotpe: 6
    normalize: True
    featureC: 128
    activation: 'softplus'
    # activation: 'sigmoid'
    # activation: 'sigmoid'
    mul_ggx: False
    use_roughness: true
    detach_roughness: false
    lr: 1e-4

  bg_module:
    _target_: models.bg_modules.HierarchicalCubeMap
    bg_resolution: 1024
    mipbias: 0
    num_levels: 1
    activation: 'exp'
    power: 2
    stds: []
    lr: 0.4
    betas: [0.9, 0.999]
    mipbias_lr: 1e-4
    mipnoise: 0.5

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    feape: 2
    featureC: 128
    num_layers: 3
    lr: 1e-4
    # allocation: 7

  # diffuse_module:
  #   _partial_: True
  #   _target_: models.render_modules.PassthroughDiffuse

  # normal_module:
  #   _partial_: True
  #   _target_: models.render_modules.AppDimNormal

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    pospe: 12
    feape: 0
    featureC: 256
    # featureC: 64
    num_layers: 4
    # allocation: 3

  # visibility_module:
  #   _partial_: True
  #   _target_: models.render_modules.VisibilityMLP
  #   lr: 1e-3
  #   view_encoder:
  #     _target_: models.ish.ListISH
  #     degs: [0,1,2,4]
  #   feape: 0
  #   featureC: 64
  #   num_layers: 3

  visibility_module:
    _partial_: True
    _target_: modules.naive_vis_cache.NaiveVisCache
    grid_size: 128
    # lr: 1e-3
    # view_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # feape: 0
    # featureC: 64
    # num_layers: 3

params:
  L1_weight_inital: 8e-5
  L1_weight_rest: 4e-5

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  normal_lambda: 3e-2
  diffuse_lambda: 2e-4
  backwards_rays_lambda: 0.1
  # floater_lambda: 1e-4
  brdf_lambda: 0
  floater_lambda: 0
  visibility_lambda: 20
  N_visibility_rays: 128
  # floater_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0

  envmap_train_start: 20
  # num_rays_per_envmap: 512
  num_rays_per_envmap: 64
  num_env_train_iters: 0
  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-4
  lr_init: 0.05
  batch_size: 4096
