_partial_: True
_target_: fields.tcnn.TCNNRF
distance_scale: 2
density_shift: 0
activation: 'exp'
# activation: 'softplus'
featureC: 64
num_layers: 3
encoder_conf:
    otype: "HashGrid"
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 16
lr: 1e-2
lr_net: 1e-3
num_pretrain: 1000
# n_samples_iters: [7500, 12500]
# n_samples_list: [512, 1024, 2048]
n_samples_iters: [1500, 3500]
n_samples_list: [512, 1024, 2048]
# n_samples_iters: [3500]
# n_samples_list: [1024, 2048]
