_partial_: True
_target_: fields.triplanar.Triplanar
distance_scale: 25
density_n_comp: 24
# density_n_comp: 24
appearance_n_comp: 24
app_dim: 24
step_ratio: 0.5
density_res_multi: 1
contract_space: False
smoothing: 0.05
# activation: 'softplus_shift'
# activation: 'softplus'
activation: 'exp'
# activation: 'relu_shift'
# init_mode: rand
init_mode: trig
density_shift: -0

N_voxel_init: 2097156 # 128**3
# N_voxel_init: 16777216 # 256**3
# N_voxel_init: 512000 # 80**3
# N_voxel_init: 4096000 # 160**3
# N_voxel_init: 134217728 # 512**3
N_voxel_final: 27000000 # 300**3
# N_voxel_init: 27000000 # 300**3
# N_voxel_final: 134217728 # 512**3
# upsamp_list: [2000,3000,4000,5500,7000]
# upsamp_list: [4000,5500,7000,8000,9000]
# upsamp_list: [4000,5500,7000,8000,9000]
# upsamp_list: [7000,8000,9000]
upsamp_list: [14000,16000,18000]
# upsamp_list: [4000,4000,5500,7000]
# upsamp_list: [] # 4000,4000,5500,7000]
lr: 1e-2
lr_net: 1e-3
num_pretrain: 000

