n_iters: 60000
render_mode: center

N_voxel_init: 2097156 # 128**3
N_voxel_final: 27000000 # 300**3

defaults:
  - dataset: counter
  - expname: test
render_only: false


tensorf:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  density_shift: -10
  alphaMask_thres: 0.0001
  distance_scale: 25
  rayMarch_weight_thres: 0.0001
  nEnvSamples: 0
  # fea2denseAct: 'softplus_shift'
  fea2denseAct: 'relu'
  rf:
    _partial_: True
    _target_: models.tensoRF.TensorVMSplit
    density_n_comp: 16
    appearance_n_comp: 8
    app_dim: 27
    step_ratio: 0.5
    density_res_multi: 1
    contract_space: True
    infinity_border: True
    num_levels: 1
    hier_sizes: [1]
    max_recurs: 1

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    feape: 2
    view_encoder:
      _target_: models.ish.ISH
      max_degree: 6
    featureC: 128
    num_layers: 0

  ref_module:
    _partial_: True
    _target_: models.render_modules.MLPRender_FP
    feape: 2
    # view_encoder:
    #   _target_: models.ish.ISH
    #   max_degree: 6
    ref_encoder:
      _target_: models.ish.RandISH
      rand_n: 8
      std: 5
    featureC: 128
    num_layers: 2

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    pospe: 6
    feape: 2
    featureC: 128
    num_layers: 1

  # bg_module:
  #   _target_: models.render_modules.BackgroundRender
  #   bg_rank: 8
  #   # view_encoder:
  #   #   _target_: models.ish.ISH
  #   #   max_degree: 6
  #   bg_resolution: [1024, 512]

#featureC: 256
#N_voxel_init: 262144 # 64**3
#N_voxel_final: 47000000 # 300**3

schedule:
  smoothing_start: 1.0
  smoothing_end: 0.5

  N_voxel_init: 2097156 # 128**3
  # N_voxel_final: 27000000 # 300**3
  # N_voxel_init: 27000000 # 128**3
  N_voxel_final: 134217728 # 300**3

  # bounce_n_list: [100, 1000, 10000, 20000]
  # bounce_iter_list: [9000, 12000, 14000]

  bounce_n_list: [0, 0]
  bounce_iter_list: [0]

  upsamp_list: [3000,4000,5500,7000]
  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  update_AlphaMask_list: [4000, 70000]
  # update_AlphaMask_list: [30000]

loss:
  normal_lambda: 2
  floater_lambda: 0.00
  charbonier_eps: 0.001
  num_bw_iters: 1000
nSamples: 4096
N_vis: 5
vis_every: 5000

L1_weight_inital: 8e-5
L1_weight_rest: 4e-5
rm_weight_mask_thre: 1e-4
